### ISSUE TITLE
missing module: mapbox_earcut

### ISSUE THREAD

**Issue by lukasc-ubc** [flaport/meow#2]
On Mac OSX M1 processor, I got as far as the visualization step, then received the following error

```
mw.visualize(structs, scale=(1, 1, 0.2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lukasc/gdsfactory/lib/python3.9/site-packages/meow/visualize.py", line 95, in visualize
    return _visualize_structures(objs, **kwargs)
  File "/Users/lukasc/gdsfactory/lib/python3.9/site-packages/meow/structures.py", line 48, in _visualize_structures
    geometry=[s._trimesh(scale=scale) for s in _sort_structures(structures)]
  File "/Users/lukasc/gdsfactory/lib/python3.9/site-packages/meow/structures.py", line 48, in <listcomp>
    geometry=[s._trimesh(scale=scale) for s in _sort_structures(structures)]
  File "/Users/lukasc/gdsfactory/lib/python3.9/site-packages/meow/structures.py", line 33, in _trimesh
    return self.geometry._trimesh(
  File "/Users/lukasc/gdsfactory/lib/python3.9/site-packages/meow/geometries.py", line 256, in _trimesh
    prism = extrude_polygon(poly, self.h_max - self.h_min)
  File "/Users/lukasc/gdsfactory/lib/python3.9/site-packages/trimesh/creation.py", line 194, in extrude_polygon
    vertices, faces = triangulate_polygon(
  File "/Users/lukasc/gdsfactory/lib/python3.9/site-packages/trimesh/creation.py", line 458, in triangulate_polygon
    faces = _tri_earcut(vertices, rings).reshape(
  File "/Users/lukasc/gdsfactory/lib/python3.9/site-packages/trimesh/exceptions.py", line 48, in failed
    raise exc
  File "/Users/lukasc/gdsfactory/lib/python3.9/site-packages/trimesh/creation.py", line 34, in <module>
    from mapbox_earcut import triangulate_float64 as _tri_earcut
ModuleNotFoundError: No module named 'mapbox_earcut'

```

easy fix:

`pip install mapbox_earcut`

perhaps you can add it as a dependancy.

**Comment by flaport** [comment]
Interesting, `mapbox_earcut` seems to be a dependency for [trimesh](https://github.com/mikedh/trimesh), which _is_ in the requirements. I guess I'll have to specify `trimesh[full]` in stead. Thanks for letting me know!

**Comment by flaport** [comment]
Fixed in the commit above.
